
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/project/backend
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      #- run:
      #    name: Test
      #    command: mvn test
      - run:
          name: Analyze on SonarCloud
          command: mvn sonar:sonar -Dsonar.projectKey=$PROJECT_KEY  -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  sample:
    jobs:
      - build-and-test
