version: 2.1
orbs:
  path-filtering: circleci/path-filtering@0.0.2

# This allows you to use CircleCI's dynamic configuration feature
setup: true

workflows:
  run-filter:
    jobs:
      - path-filtering/filter:
          # Compare files on main
          base-revision: development
          mapping: |
            backend/.* run-backend true
          config-path: ".circleci/dynamicConfig.yml"