version: 2.1
orbs:
  python: circleci/maven@1.2.0
  sonarcloud: sonarsource/sonarcloud@1.0.3

parameters:
  run-backend: 
    type: boolean
    default: false

jobs:

  backend-test:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/project/backend
    steps:
      # Checkout the code as the first step.
      - checkout:
          path: ~/project 
      # Use mvn clean and package as the standard maven build phase
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      # Then run your tests!
      - run:
          name: Test
          command: mvn test
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

workflows:
  backend-test:
    when: << pipeline.parameters.run-backend >>
    jobs:
      - backend-test